plugins:
  topic_group_button_url:
    default: "https://www.discourse.org?topic_id=<TOPIC_ID>&session_id=<SESSION_ID>"
    client: true
  topic_group_button_title:
    default: "Start escalation process for this Topic"
    client: true
  topic_group_button_label:
    default: "Escalate"
    client: true
  topic_group_button_allowed_group:
    default: 
      - "trust_level_4"
      - "some_other_group"
      - "some_other_other_group"
    client: true
